helmOperator:
  create: false
#
# @CHANGEME - Update url to your public repo URL
#
git:
  url: "git@github.com:voigt/pinetes.git"
  branch: master
  path: deployments
image:
  repository: raspbernetes/flux
  tag: 1.18.0
registry:
  rps: 1
  burst: 1
memcached:
  enabled: true
syncGarbageCollection:
  enabled: true
  dry: false
prometheus:
  enabled: true
  serviceMonitor:
    create: false
    interval: 30s
    scrapeTimeout: 10s
    namespace: flux
